### ISSUE TITLE
로그인, 구매 버전업, 옵션 선택.

### ISSUE THREAD

**Issue by J-Kim-Korea** [OneTop4458/smartstore-macro#1]
로그인 버튼 코드가 조금 바뀌었는지, 로그인에서 안넘어가서, 버튼만 수정해 보니 잘 넘어갔구요.
구매 버튼과 일반결제-나중에 결제-주문하기 부분도 조금 변경 해 보니, 단일 옵션인 제품은 구매까지 잘 되는데요.
옵션을 선택해야 하는 제품인 경우의 코드는 제가 수정하기가 좀 어렵네요!ㅠㅠ
해당 부분 수정 업데이트가 가능하실지 여쭙습니다.

**Comment by OneTop4458** [comment]
안녕하세요 우선 네이버 측에서 코로나 잔여 백신 기능을 도입하는 시기에
매크로를 막고자 전사 시스템 전체에 매크로 방지 기술을 많이 추가해둔 상태입니다.

새고 고침 할 때마다 매크로 개발에 필요한 id 값 등이 모두 랜덤으로 출력되게끔 변경되어서
수정이 가능할지는 확인이 필요할 것 같습니다.

**Comment by OneTop4458** [comment]
@J-Kim-Korea 버그 수정 후 릴리즈 하였습니다.
